name: flutter_diy
description: A new Flutter package project.
publish_to: none
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0

workspace:
  #  - packages/*
  - app
  - app/packages/ffi_plugin
  - game
  - game/packages/flame_ext
  - shorebird_example
  - riverpod_app
  - brick_breaker_game
  - sqlite_ffi
  - hybrid/flutter_module
  - analyzer_exploration

dev_dependencies:
  melos: ^7.1.0

melos:
#  sdkPath: .fvm/flutter_sdk

  ide:
    intellij:
      enabled: false