# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_app
  
  # Pods for flutter_module
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # 判断当前 Mac 的架构
        if `uname -m`.strip == "x86_64"
          # Intel Mac 上跑 iOS Simulator，需要排除 arm64
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        else
          # Apple Silicon Mac (arm64)，不要排除
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = ""
        end
      end
    end
end
